name: CI

on: [push]

jobs:
  ci:
    name: ${{ matrix.plat.name }} Build + Test
    runs-on: ${{ matrix.plat.os }}
    strategy:
      fail-fast: false
      matrix:
        plat:
          - { os: ubuntu-latest, name: Ubuntu }
          - { os: macos-latest,  name: macOS }

    steps:
      - uses: actions/checkout@v5

      - name: Download submodules
        shell: bash
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Gristmill
        run: uv sync --locked --extra dev

      - name: Set up Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc

      - name: Install coverage tools
        run: uv pip install coverage coveralls

      - name: Run tests with coverage
        env:
          DUMMY_SPARK: 1
        run: uv run coverage run --source=gristmill --omit="*/templates/*" -m pytest tests

      - name: Upload coverage to Coveralls (Ubuntu only)
        if: ${{ always() && matrix.plat.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run coveralls --service=github

